### ISSUE TITLE
spam in console

### ISSUE THREAD

**Issue by PerchunPak** [LXGaming/ClearLag#2]
spaming in console `[ClearLag] RAMCheckTask was unable to dispatch commands!` maybe because my hosting using https://pterodactyl.io/
hosting: https://hosting.superhub.xyz (if you dint know russian, you can dm me in discord Perchun_Pak#9236)

**Comment by LXGaming** [comment]
I think you have the wrong GitHub Repository. This plugin doesn't have a RAMCheckTask

**Comment by LXGaming** [comment]
You want the issue tracker for ClearLagg - https://dev.bukkit.org/projects/clearlagg/issues
